#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def miniMaxSum(arr):
    # Write your code here
    l1=list(arr)
    l2=sorted(l1)
    mins=l2[0]+l2[1]+l2[2]+l2[3]
    maxs=l2[1]+l2[2]+l2[3]+l2[4]
    print( mins,maxs)
    

if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
